### ISSUE TITLE
Progress hook does not preprocess to check if the video/audio already exists and directly prints the output on slack.

### ISSUE THREAD

**Issue by Diptanshu8** [sum12/python-rtmbot#4]
I found this bug that the return from the youtube.py plugin is not checked as the progress hook is called internally even though the video/audio exists. In this case, 
* Either using `download-archive` may help.
* Else some internal processing needs to be.
 Another approach could be `extract_info` in the link_downloader function to make youtube.py plugin only return the name of the playlist that has been downloaded.
P.S.: Solving this issue will help moderate the output of the crons that are running very frequently.

**Comment by sum12** [comment]
Yes I remember this was the issue back then.

[this](https://github.com/rg3/youtube-dl/pull/11231) should fix the issue

**Comment by sum12** [comment]
fixed in https://github.com/sum12/python-rtmbot/commit/ae968f3b4c50b50ca4ae336756451685579b1afa
